# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab1d7812f3ab35949408c5761a001f2a9c9d042670df8b0babcd5d01f7d2709832f3b668b5bbb70b16b0db4296235174ea597d6e1a6118534ab0aa727589fb29

test:
  secret_key_base: 0ff54c95695cae634e0b51f92bddca6badd724cd37f4935cf3f6d334ec40a8b2b02c7c329dddb1bb7c9ebd747881fcfea586d19806a403dd1896ed53a0612a43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
